### ISSUE TITLE
Feature request: Adding a Helm chart

### ISSUE THREAD

**Issue by ASiebens** [mologie/talos-vmtoolsd#4]
# Feature Request: Adding a Helm Chart

First of all, big thanks for the work done so our Talos clusters work perfectly with our existing vSphere infrastructure!

## Reason for feature request
Whenever a new version of any software I deploy releases, I need to manually download the manifests and change whatever needs changing to cater to my personal needs (subnets, nodes, ...). Lately I've been deploying as much as I can using Helm charts so I can more easily make changes to a deployment without all the manual work.

Now, I know that for this application to have a Helm chart isn't really needed (as it's only 1 `DaemonSet`), but having the flexibility of having a Helm chart towards the future could be a nice-to-have.

## Work already done
I have forked this repository and made the following changes to the `master` branch:
* Added a `helm` subfolder with all files that make up the Chart (`templates`, `Chart.yaml`, `README.md`, ...)
* Added a new workflow (`helm.yaml`) that builds a new release every time a tag is created (usually on every release).
  * The workflow only triggers on tag releases, not on commits. the `ghcr.yaml` doesn't trigger on changes to any file in the `helm` subfolder (as that wouldn't change the application, therefore not needing a rebuild).
  * After building the Chart, the archive is published to a `gh-pages` branch and deployed using GitHub pages (this branch is created the first time an archive is published) using the `https://mologie.github.io/talos-vmtoolsd` URL.

## Follow-up
If you accept the request, I will create a pull request for review to integrate these changes into the `master` branch.

Please note:
* An archive can't be made for the `0.2` release. So if you wanted to retro-actively make one:
  * A tag needs to be made to trigger the workflow to create one (eg. 0.2.1), no new release is needed. A container rebuild wouldn't be needed either, so the `ghcr.yaml` workflow could be manually cancelled.
  * The Helm templates files need to be adjusted to reflect the tag version (changing version to `0.2.1`, but leaving appVersion intact).
* For when the `0.3` version is ready for release, the same files (the `helm` subfolder and the `helm.yaml` workflow) would need to be added. I've added those already to my forked `develop-0.3` branch, so a pull request could be made to easily make those changes as well.

For any subsequent version, no changes would be needed and everything would be done automagically.

**Comment by mologie** [comment]
Hi, thank you for the request, I really appreciate your effort to improve the project. However, as you have already noted, there is little benefit in adding a Helm chart to talos-vmtoolsd.

The project is designed to be free of any configuration, and even provisioning of Talos' config will eventually no longer be required. This is tracked by #3. As such, Helm's primary benefit of making application configuration more accessible does not really work for this project in current of future state.

At Authentic Vision we deploy talos-vmtoolsd to our clusters using Kustomize, which applies a strategic merge patch that adds tolerations to the DaemonSet. Helm does not provide such flexibility without explicitly programming it, so I would expect a majority of the Helm file to include options not related to talos-vmtoolsd's primary functionality if one is added.

If automatic deployment to a large set of clusters is your aim then tools such as ArgoCD can perform the modification and deployment task for you without involving Helm.

Note regarding your Helm chart itself: It appears to drop the image hash and adds an imagePullPolicy=always line; you likely do not want such a configuration as it could result in unexpected cluster changes if the image behind the 0.2 tag changes (not that it ever will, this is more of a general note).
