### ISSUE TITLE
Is Persistent Storage Supported?

### ISSUE THREAD

**Issue by rgl** [mologie/talos-vmtoolsd#5]
Is persistent storage supported or is going to be supported?

Somehow support for Container Storage Interface (CSI) using, e.g., virtual disks (VMDK)?

I can see that the README has `[x] Validate interopability with with VMware K8s CNI/CSI`, does that mean that https://cloud-provider-vsphere.sigs.k8s.io/concepts/vmware_vsphere_storage.html works out-of-the-box?

**Comment by mologie** [comment]
Yes, the VMware CNI/CSI works nicely along with talos-vmtoolsd. I documented how I set it up in my team's environment here: https://github.com/mologie/talos/commit/28f10f2c85797f6459ad78e5feaf258a2e46df6d

**Comment by rgl** [comment]
@mologie Thank you!

**Comment by mologie** [comment]
(Note I just released version 0.3. You'll need that for a fresh install, Talos 0.14-1.0 support is no longer in beta as of now o/.)
